spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.89:3306/mathew?characterEncoding=utf-8
    username: root
    password: iSanfeng2015
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
