spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/butler?characterEncoding=utf-8
      username: root
      password: mysql
  jpa:
     hibernate:
        ddl-auto: update
        show-sql: true
server:
  port: 8080
  context-path: /butler

age: 18
content: "age: ${age}"

user:
  name: zhangsan
  age: 22

spring.devtools.restart.additional-paths: src\\main\\java

